'use strict';

const ADMIN_EMAIL = 'anowarali2707@outlook.com';
const APPLICATION_STATUSES = [
  'Application Submitted',
  'Under Process',
  'Successfully Completed',
  'Rejected',
  'Declined'
];

let orders = [];
let profiles = [];
let profileLoadError = null;
let ordersLoadError = null;

const $ = id => document.getElementById(id);
const esc = value => String(value ?? '').replace(/[&<>"']/g, ch => ({
  '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'
}[ch]));
function formatRequirement(raw, compact=true) {
  const value=String(raw??'').trim(); if(!value) return '<span class="req-empty">No details</span>';
  const marker=/\bAFP_HTML\s*:/i.exec(value); const human=(marker?value.slice(0,marker.index):value).replace(/[\s|;]+$/,'').trim();
  const saved=marker?value.slice(marker.index+marker[0].length).trim():'';
  const fields=human.split(/\s*\|\s*|\r?\n/).map(x=>x.trim()).filter(Boolean).map(part=>{const p=part.indexOf(':');return p>0?{label:part.slice(0,p).trim(),value:part.slice(p+1).trim()}:{label:'Details',value:part};}).filter(f=>f.value);
  if(fields.length===1&&fields[0].label==='Details'&&!saved) return `<div class="req-wrap"><p class="req-note">${esc(fields[0].value)}</p></div>`;
  const shown=compact?fields.slice(0,3):fields;
  const chips=shown.map(f=>`<span class="req-chip"><b>${esc(f.label)}</b><span>${esc(f.value)}</span></span>`).join('');
  const full=fields.map(f=>`<div class="req-full-row"><b>${esc(f.label)}</b><span>${esc(f.value)}</span></div>`).join('');
  const source=saved?`<details class="req-source"><summary>Saved front-page preview data (${saved.length.toLocaleString('en-IN')} characters)</summary><pre>${esc(saved.slice(0,20000))}${saved.length>20000?'\n… source shortened for display; the original order data remains unchanged.':''}</pre></details>`:'';
  const details=(fields.length>(compact?3:fields.length)||saved)?`<details class="req-details"><summary>View full details</summary><div class="req-full-grid">${full||'<p>Preview data is stored with this order.</p>'}</div>${source}</details>`:'';
  return `<div class="req-wrap"><div class="req-grid">${chips}</div>${fields.length>shown.length?`<span class="req-count">+${fields.length-shown.length} more fields</span>`:''}${details}</div>`;
}
function requirementPlain(raw) { const value=String(raw??'').trim(); const marker=/\bAFP_HTML\s*:/i.exec(value); const human=(marker?value.slice(0,marker.index):value).replace(/[\s|;]+$/,'').trim(); return human.split(/\s*\|\s*|\r?\n/).map(x=>x.trim()).filter(Boolean).join('\n')+(marker?'\nFront-page preview data saved with this order ('+value.slice(marker.index+marker[0].length).trim().length+' characters).':''); }


function normalizedStatus(value) {
  const status = String(value || '').toLowerCase();
  if (status.includes('reject')) return 'Rejected';
  if (status.includes('declin')) return 'Declined';
  if (status.includes('complete') || status === 'done') return 'Successfully Completed';
  if (status.includes('process')) return 'Under Process';
  return 'Application Submitted';
}

function statusClass(value) {
  const status = normalizedStatus(value);
  if (status === 'Rejected') return 'rejected';
  if (status === 'Declined') return 'rejected';
  if (status === 'Under Process') return 'processing';
  if (status === 'Successfully Completed') return 'completed';
  return 'pending';
}

function safeOrderId(value) {
  // Order IDs generated by this site are alphanumeric. Strip anything unexpected
  // before placing an ID in an inline handler attribute.
  return String(value ?? '').replace(/[^A-Za-z0-9_-]/g, '');
}

const pdfFileLinkCache = new Map();
async function getPdfFileLinks(filePath) {
  const path = String(filePath || '').trim();
  if (!path) return { error: 'No PDF file path was saved with this order.' };
  const cached = pdfFileLinkCache.get(path);
  if (cached && cached.expires > Date.now()) return cached.value;
  const bucket = supabaseClient.storage.from('pdf-orders');
  const view = await bucket.createSignedUrl(path, 3600);
  if (view.error || !view.data?.signedUrl) return { error: view.error?.message || 'Could not create PDF viewing link.' };
  let downloadUrl = view.data.signedUrl;
  const download = await bucket.createSignedUrl(path, 3600, { download: true });
  if (!download.error && download.data?.signedUrl) downloadUrl = download.data.signedUrl;
  const value = { viewUrl: view.data.signedUrl, downloadUrl };
  pdfFileLinkCache.set(path, { expires: Date.now() + 50 * 60 * 1000, value });
  return value;
}
async function pdfFileActions(filePath) {
  if (!filePath) return '<span class="file-muted">No file attached</span>';
  const links = await getPdfFileLinks(filePath);
  if (links.error) return `<span class="file-muted" title="${esc(links.error)}">PDF unavailable · check Storage permissions</span>`;
  return `<div class="pdf-file-actions"><a href="${esc(links.viewUrl)}" target="_blank" rel="noopener">📄 View PDF</a><a href="${esc(links.downloadUrl)}" target="_blank" rel="noopener" download>⬇ Download</a></div>`;
}
async function adminResultActions(filePath) {
  if (!filePath) return '<span class="file-muted">No result PDF uploaded</span>';
  try {
    const bucket = supabaseClient.storage.from('service-results');
    const view = await bucket.createSignedUrl(filePath, 3600);
    if (view.error || !view.data?.signedUrl) return '<span class="file-muted">Result PDF unavailable</span>';
    const dl = await bucket.createSignedUrl(filePath, 3600, { download: true });
    return `<div class="pdf-file-actions"><a href="${esc(view.data.signedUrl)}" target="_blank" rel="noopener">📄 View result</a><a href="${esc(dl.data?.signedUrl || view.data.signedUrl)}" target="_blank" rel="noopener" download>⬇ Download</a></div>`;
  } catch (error) { console.error(error); return '<span class="file-muted">Result PDF unavailable</span>'; }
}
async function adminCustomerUpdateControls(order, prefix = 'orders') {
  const id = safeOrderId(order.order_id), noteId = `admin-note-${prefix}-${id}`, fileId = `admin-result-file-${prefix}-${id}`;
  const result = await adminResultActions(order.result_file_path);
  return `<div class="admin-customer-update"><label class="admin-note-label" for="${noteId}">Customer note</label><textarea id="${noteId}" rows="3" maxlength="3000" placeholder="e.g. Your application acknowledgement number is...">${esc(order.admin_note || '')}</textarea><button type="button" class="admin-mini-btn" onclick="saveOrderCustomerNote('${id}','${prefix}')">💾 Save note</button><div class="admin-result-current">${result}</div><input id="${fileId}" type="file" accept="application/pdf,.pdf" hidden onchange="uploadOrderServiceResult('${id}','${prefix}',this)"><button type="button" class="admin-mini-btn" onclick="document.getElementById('${fileId}').click()">📤 ${order.result_file_path ? 'Replace result PDF' : 'Upload result PDF'}</button><small class="file-muted">PDF only, max 25 MB. Customer can download from My Orders.</small></div>`;
}
async function saveOrderCustomerNote(orderId, prefix = 'orders') {
  const id = safeOrderId(orderId), field = document.getElementById(`admin-note-${prefix}-${id}`);
  if (!field) return;
  const { data, error } = await supabaseClient.from('orders').update({ admin_note: field.value.trim() }).eq('order_id', id).select('order_id').maybeSingle();
  if (error) { alert('Could not save customer note: ' + error.message + '\nRun the included service notes SQL in Supabase first.'); return; }
  if (!data) { alert('No order was updated. Please refresh the Admin Panel.'); return; }
  await load();
}
async function uploadOrderServiceResult(orderId, prefix, input) {
  const id = safeOrderId(orderId), file = input?.files?.[0]; if (!file) return;
  if (file.type !== 'application/pdf' && !/\.pdf$/i.test(file.name)) { alert('Please choose a PDF file.'); input.value = ''; return; }
  if (file.size > 25 * 1024 * 1024) { alert('The PDF must be 25 MB or smaller.'); input.value = ''; return; }
  const order = orders.find(item => String(item.order_id) === id);
  if (!order) { alert('Order not found. Refresh and try again.'); input.value = ''; return; }
  if (!order.user_id) { alert('This order has no customer account ID, so the result cannot be linked to a private download.'); input.value = ''; return; }
  const fileName = file.name.replace(/[^A-Za-z0-9._-]/g, '_').slice(-100) || 'result.pdf';
  const path = `${order.user_id}/orders/${id}-result-${Date.now()}-${fileName}`;
  try {
    const uploaded = await supabaseClient.storage.from('service-results').upload(path, file, { contentType: 'application/pdf', upsert: false });
    if (uploaded.error) throw uploaded.error;
    const updated = await supabaseClient.from('orders').update({ result_file_path: path }).eq('order_id', id);
    if (updated.error) { await supabaseClient.storage.from('service-results').remove([path]); throw updated.error; }
    if (order.result_file_path) await supabaseClient.storage.from('service-results').remove([order.result_file_path]);
    alert('Result PDF uploaded. The customer can download it from My Orders.'); await load();
  } catch (error) { console.error(error); alert('Could not upload the result PDF: ' + (error?.message || String(error)) + '\nCheck service-results Storage permissions.'); }
  finally { input.value = ''; }
}
window.adminCustomerUpdateControls = adminCustomerUpdateControls;
window.saveOrderCustomerNote = saveOrderCustomerNote;
window.uploadOrderServiceResult = uploadOrderServiceResult;

function printDetails(raw) {
  const text = String(raw || '');
  const pages = (text.match(/Pages\s*:\s*(\d+)/i) || [])[1];
  const kind = (text.match(/(?:^|\|)\s*(Colour|Color|Black\s*&\s*White|B\s*&?\s*W)(?=\s*(?:\||$))/i) || [])[1];
  const file = (text.match(/File\s*:\s*([^|\r\n]+)/i) || [])[1];
  const parts = [];
  if (pages) parts.push(`${esc(pages)} page(s)`);
  if (kind) parts.push(esc(kind));
  if (file) parts.push(`<span class="file-muted">${esc(file.trim())}</span>`);
  return parts.length ? parts.join('<br>') : formatRequirement(text || 'No print details', true);
}
async function renderPrintOrders() {
  const body = $('printOrdersBody');
  if (!body) return;
  const query = ($('printOrderSearch')?.value || '').toLowerCase().trim();
  const printOrders = orders.filter(order => String(order.service || '').toLowerCase().includes('pdf print'));
  const matching = printOrders.filter(order => [order.order_id, order.customer_name, order.phone, order.requirement, order.file_path].join(' ').toLowerCase().includes(query));
  const message = $('printOrdersMessage');
  if (message) message.textContent = `${printOrders.length} PDF Print order(s) found.`;
  if (!matching.length) {
    body.innerHTML = `<tr><td colspan="9">${query ? 'No matching PDF Print orders.' : 'No PDF Print orders found yet.'}</td></tr>`;
    return;
  }
  body.innerHTML = '<tr><td colspan="9">Preparing secure PDF links…</td></tr>';
  const html = await Promise.all(matching.map(async order => {
    const id = safeOrderId(order.order_id);
    const status = statusSelect(id, order.status);
    const file = await pdfFileActions(order.file_path);
    const tools = await adminCustomerUpdateControls(order, 'page-print');
    return `<tr><td><b>${esc(order.order_id || '')}</b></td><td>${esc(order.customer_name || 'Customer')}</td><td>${esc(order.phone || '—')}</td><td>${printDetails(order.requirement)}</td><td>₹${(Number(order.amount) || 0).toFixed(2)}</td><td>${esc(order.payment_method || 'N/A')}</td><td>${file}</td><td>${status}${tools}</td><td>${order.created_at ? new Date(order.created_at).toLocaleString('en-IN') : ''}</td></tr>`;
  }));
  body.innerHTML = html.join('');
}

function statusSelect(orderId, currentStatus) {
  const id = safeOrderId(orderId);
  const current = normalizedStatus(currentStatus);
  return `<select class="admin-status-select" aria-label="Change status for ${esc(id)}" onchange="updateStatus('${id}', this.value)">${APPLICATION_STATUSES.map(status => `<option value="${status}" ${status === current ? 'selected' : ''}>${status}</option>`).join('')}</select>`;
}

async function init() {
  try {
    const { data: { user } = {}, error } = await supabaseClient.auth.getUser();
    if (error || !user || String(user.email || '').toLowerCase() !== ADMIN_EMAIL.toLowerCase()) {
      location.href = '../auth/admin-login.html';
      return;
    }
    await load();
  } catch (error) {
    console.error('Admin session verification failed:', error);
    alert('Admin session could not be verified. Please sign in again.');
    location.href = '../auth/admin-login.html';
  }
}

function setText(id, value) {
  const element = $(id);
  if (element) element.textContent = value;
}

async function load() {
  const [ordersResult, profilesPrimary] = await Promise.all([
    supabaseClient.from('orders').select('*').order('created_at', { ascending: false }),
    supabaseClient.from('profiles').select('*').order('account_created', { ascending: false })
  ]);

  let profilesResult = profilesPrimary;
  if (profilesResult.error && /account_created|column .* does not exist/i.test(profilesResult.error.message || '')) {
    profilesResult = await supabaseClient.from('profiles').select('*');
  }

  ordersLoadError = ordersResult.error || null;
  profileLoadError = profilesResult.error || null;
  orders = ordersResult.data || [];
  window.AdminOrders = orders;
  profiles = (profilesResult.data || [])
    .map(profile => ({
      ...profile,
      auth_id: profile.auth_id || profile.id || profile.user_id,
      account_created: profile.account_created || profile.created_at || profile.inserted_at || null
    }))
    .filter(profile => String(profile.email || '').toLowerCase() !== ADMIN_EMAIL.toLowerCase());

  if (ordersLoadError) console.error('Could not load orders:', ordersLoadError);
  if (profileLoadError) console.error('Could not load customer profiles:', profileLoadError);

  setText('totalOrders', orders.length);
  setText('customerCountStat', profiles.length);
  setText('pending', orders.filter(order => statusClass(order.status) === 'pending').length);
  setText('processing', orders.filter(order => statusClass(order.status) === 'processing').length);
  setText('revenue', '₹' + orders.reduce((sum, order) => sum + (Number(order.amount) || 0), 0).toFixed(2));
  setText('r1', orders.filter(order => normalizedStatus(order.status) === 'Successfully Completed').length);
  setText('r2', orders.filter(order => ['Rejected', 'Declined'].includes(normalizedStatus(order.status))).length);
  setText('r3', orders.length);

  renderOrders();
  renderPrintOrders();
  renderCustomers();
  renderApplications();
  renderPayments();
  renderFront();
  if (window.renderPortalAppointments) window.renderPortalAppointments();
  if (window.refreshPortalManagementUI) window.refreshPortalManagementUI();
}

function nav(id, button) {
  document.querySelectorAll('.section').forEach(section => {
    const selected = section.id === id;
    section.classList.toggle('active', selected);
    section.style.display = selected ? 'block' : 'none';
    section.setAttribute('aria-hidden', selected ? 'false' : 'true');
  });
  document.querySelectorAll('.nav button').forEach(item => item.classList.remove('active'));
  if (button) button.classList.add('active');
  document.querySelector('.side')?.classList.remove('open');
  if (!$(id)) console.error('Admin section not found:', id);
  if (['serviceManage','pricing'].includes(id) && window.loadPortalManagement) window.loadPortalManagement();
  if (id === 'notice' && window.loadPortalNoticeAdmin) window.loadPortalNoticeAdmin();
  if (id === 'appointments' && window.renderPortalAppointments) window.renderPortalAppointments();
  if (id === 'print') window.renderPrintOrders?.();
}

async function renderOrders() {
  const body = $('ordersBody');
  if (!body) return;
  if (ordersLoadError) {
    body.innerHTML = `<tr><td colspan="8">Could not load orders: ${esc(ordersLoadError.message || 'Database access denied')}. Check the admin orders SELECT policy.</td></tr>`;
    return;
  }
  const query = ($('orderSearch')?.value || '').toLowerCase().trim();
  const matching = orders.filter(order => [order.order_id, order.customer_name, order.phone, order.service, order.requirement]
    .join(' ').toLowerCase().includes(query));
  body.innerHTML = matching.length ? (await Promise.all(matching.map(async order => {
    const id = safeOrderId(order.order_id);
    const status = normalizedStatus(order.status);
    const tools = await adminCustomerUpdateControls(order, 'page-orders');
    return `<tr>
      <td><b>${esc(order.order_id)}</b></td>
      <td>${esc(order.customer_name || '—')}</td>
      <td>${esc(order.phone || '—')}</td>
      <td>${esc(order.service || '—')}</td>
      <td>₹${(Number(order.amount) || 0).toFixed(2)}</td>
      <td>${statusSelect(id, order.status)}<small class="admin-status-reason">${esc((String(order.status || '').match(/(?:Reason|reason):\s*(.*)$/) || [])[1] || '')}</small></td>
      <td>${order.created_at ? new Date(order.created_at).toLocaleString('en-IN') : ''}</td>
      <td><button type="button" onclick="viewOrder('${id}')">View</button>${tools}</td>
    </tr>`;
  }))).join('') : '<tr><td colspan="8">No orders found.</td></tr>';
}

function renderCustomers() {
  const body = $('customersBody');
  if (!body) return;
  if (profileLoadError) {
    body.innerHTML = `<tr><td colspan="5">Could not load customers: ${esc(profileLoadError.message || 'Database permission denied')}. Run the included admin-customer-fix.sql in Supabase SQL Editor, then refresh this page.</td></tr>`;
    return;
  }
  const query = ($('customerSearch')?.value || '').toLowerCase().trim();
  const matching = profiles.filter(profile => [profile.name, profile.email, profile.mobile_number].join(' ').toLowerCase().includes(query));
  body.innerHTML = matching.length ? matching.map(profile => {
    const id = safeOrderId(profile.auth_id);
    return `<tr>
      <td>${esc(profile.name || 'Customer')}</td>
      <td>${esc(profile.mobile_number || 'Not provided')}</td>
      <td>${esc(profile.email || '—')}</td>
      <td>${profile.account_created ? new Date(profile.account_created).toLocaleDateString('en-IN') : ''}</td>
      <td><button type="button" onclick="viewCustomer('${id}')">View profile</button></td>
    </tr>`;
  }).join('') : '<tr><td colspan="5">No customer profiles found. If Auth users exist but this list is empty, run the included admin-customer-fix.sql in Supabase SQL Editor and refresh.</td></tr>';
}

async function renderApplications() {
  const body = $('applicationsBody');
  if (!body) return;
  if (ordersLoadError) {
    body.innerHTML = `<tr><td colspan="6">Could not load applications: ${esc(ordersLoadError.message || 'Database access denied')}.</td></tr>`;
    return;
  }
  const applications = orders.filter(order => !String(order.service || '').toLowerCase().includes('pdf print'));
  body.innerHTML = applications.length ? (await Promise.all(applications.map(async order => {
    const id = safeOrderId(order.order_id);
    const tools = await adminCustomerUpdateControls(order, 'page-applications');
    const reason = (String(order.status || '').match(/(?:Reason|reason):\s*(.*)$/) || [])[1] || '';
    return `<tr>
      <td>${esc(order.order_id || '')}</td>
      <td>${esc(order.customer_name || '')}</td>
      <td>${esc(order.service || '')}</td>
      <td>${formatRequirement(order.requirement || '', true)}</td>
      <td><span class="pill ${statusClass(order.status)}">${esc(normalizedStatus(order.status))}</span>${reason ? `<small class="admin-status-reason">Reason: ${esc(reason)}</small>` : ''}</td>
      <td>${statusSelect(id, order.status)}${tools}</td>
    </tr>`;
  }))).join('') : '<tr><td colspan="6">No applications.</td></tr>';
}

function renderPayments() {
  const body = $('paymentsBody');
  if (!body) return;
  body.innerHTML = orders.map(order => `<tr>
    <td>${esc(order.order_id || '')}</td><td>${esc(order.customer_name || '')}</td><td>${esc(order.service || '')}</td>
    <td>₹${(Number(order.amount) || 0).toFixed(2)}</td><td>${esc(order.payment_method || 'N/A')}</td><td>${esc(order.status || '')}</td>
  </tr>`).join('') || '<tr><td colspan="6">No payments.</td></tr>';
}

async function renderFront() {
  const body = $('frontBody');
  if (!body) return;
  const frontOrders = orders.filter(order => /front|assignment|project report/i.test(String(order.service || '')));
  body.innerHTML = frontOrders.length ? (await Promise.all(frontOrders.map(async order => {
    const id = safeOrderId(order.order_id), tools = await adminCustomerUpdateControls(order, 'page-front');
    return `<tr><td>${esc(order.order_id || '')}</td><td>${esc(order.customer_name || '')}</td><td>${esc(order.service || '')}</td>
      <td>${formatRequirement(order.requirement || '', true)}</td><td>${statusSelect(id, order.status)}</td><td><button type="button" onclick="viewOrder('${id}')">View</button>${tools}</td></tr>`;
  }))).join('') : '<tr><td colspan="6">No Front Page Maker orders.</td></tr>';
}

async function updateStatus(orderId, requestedStatus) {
  const id = safeOrderId(orderId);
  const nextStatus = APPLICATION_STATUSES.includes(requestedStatus) ? requestedStatus : 'Application Submitted';
  let reason = '';
  if (nextStatus === 'Rejected' || nextStatus === 'Declined') {
    const existing = orders.find(order => String(order.order_id) === id);
    const match = String(existing?.status || '').match(/(?:Reason|reason):\s*(.*)$/);
    reason = prompt(`Enter a reason for ${nextStatus} (required):`, match?.[1] || '') || '';
    if (!reason.trim()) {
      alert('Status was not changed. Please enter a reason for rejection/decline.');
      await load();
      return;
    }
  }
  const savedStatus = nextStatus + (reason.trim() ? ' — Reason: ' + reason.trim() : '');
  const { data, error } = await supabaseClient.from('orders')
    .update({ status: savedStatus })
    .eq('order_id', id)
    .select('order_id')
    .maybeSingle();
  if (error) {
    alert('Could not change status: ' + error.message + '\nRun the included admin-customer-fix.sql in Supabase SQL Editor if this is a permission error.');
    await load();
    return;
  }
  if (!data) {
    alert('No order status was changed. The order may not exist, or the admin UPDATE policy is missing.');
    await load();
    return;
  }
  await load();
}

function viewOrder(orderId) {
  const order = orders.find(item => String(item.order_id) === String(orderId));
  if (!order) return;
  alert(`Order: ${order.order_id}\nCustomer: ${order.customer_name || '—'}\nService: ${order.service || '—'}\nMobile: ${order.phone || '—'}\nDetails: ${requirementPlain(order.requirement || 'None')}\nStatus: ${order.status || 'Application Submitted'}\nAmount: ₹${(Number(order.amount) || 0).toFixed(2)}`);
}

function viewCustomer(authId) {
  const profile = profiles.find(item => String(item.auth_id) === String(authId));
  if (!profile) return alert('Customer profile not found. Please refresh the customer list.');
  $('editAuthId').value = profile.auth_id || '';
  $('editCustomerName').value = profile.name || '';
  $('editCustomerEmail').value = profile.email || '';
  $('editCustomerMobile').value = profile.mobile_number || '';
  $('editCustomerCreated').value = profile.account_created ? new Date(profile.account_created).toLocaleString('en-IN') : '';
  setText('customerModalTitle', profile.name || 'Customer Profile');
  setText('customerModalMessage', '');

  const identifiers = [profile.auth_id, profile.id, profile.user_id].filter(Boolean).map(String);
  const customerOrders = orders.filter(order => {
    const orderIdentifiers = [order.user_id, order.auth_id, order.customer_id].filter(Boolean).map(String);
    return orderIdentifiers.some(value => identifiers.includes(value)) ||
      String(order.email || '').toLowerCase() === String(profile.email || '').toLowerCase();
  });
  $('customerHistoryBody').innerHTML = customerOrders.length ? customerOrders.map(order => `<tr>
    <td>${esc(order.order_id || '')}</td><td>${esc(order.service || '')}</td><td>${formatRequirement(order.requirement || '', true)}</td>
    <td>₹${(Number(order.amount) || 0).toFixed(2)}</td><td>${esc(normalizedStatus(order.status))}</td>
    <td>${order.created_at ? new Date(order.created_at).toLocaleString('en-IN') : ''}</td>
  </tr>`).join('') : '<tr><td colspan="6">No orders are linked to this profile yet.</td></tr>';
  $('customerDetailModal').hidden = false;
}

function closeCustomerModal() {
  if ($('customerDetailModal')) $('customerDetailModal').hidden = true;
}

async function saveCustomerProfile(event) {
  event.preventDefault();
  const id = $('editAuthId').value;
  const message = $('customerModalMessage');
  const updates = {
    name: $('editCustomerName').value.trim(),
    email: $('editCustomerEmail').value.trim().toLowerCase(),
    mobile_number: $('editCustomerMobile').value.trim()
  };
  if (!updates.name || !updates.email || !updates.mobile_number) {
    message.textContent = 'Name, email and mobile number are required.';
    return;
  }
  message.textContent = 'Saving profile…';
  const { data, error } = await supabaseClient.from('profiles').update(updates)
    .eq('auth_id', id).select('auth_id').maybeSingle();
  if (error) {
    message.textContent = 'Profile could not be saved: ' + error.message + '. Check the Admin UPDATE policy in Supabase.';
    return;
  }
  if (!data) {
    message.textContent = 'Profile was not updated. The Admin UPDATE policy may be missing.';
    return;
  }
  await load();
  message.textContent = 'Profile updated successfully.';
  viewCustomer(id);
  setText('customerModalMessage', 'Profile updated successfully.');
}

async function issueTemporaryPassword() {
  const id = $('editAuthId').value;
  const message = $('customerModalMessage');
  if (!confirm('Request a temporary password for this customer?')) return;
  message.textContent = 'Requesting temporary password…';
  try {
    const { data, error } = await supabaseClient.functions.invoke('admin-customer-management', {
      body: { action: 'temporary_password', user_id: id }
    });
    if (error) throw error;
    message.textContent = data?.message || 'Request completed. Ask the customer to change the temporary password after login.';
  } catch (error) {
    message.textContent = 'Temporary password is not configured yet. Deploy the admin-customer-management Supabase Edge Function and set SUPABASE_SERVICE_ROLE_KEY as an Edge Function secret. Details: ' + (error.message || 'Function unavailable');
  }
}

async function logout() {
  await supabaseClient.auth.signOut();
  location.href = '../auth/admin-login.html';
}

document.addEventListener('DOMContentLoaded', init);
window.nav = nav;
window.renderCustomers = renderCustomers;
window.renderOrders = renderOrders;
window.viewCustomer = viewCustomer;
window.closeCustomerModal = closeCustomerModal;
window.saveCustomerProfile = saveCustomerProfile;
window.issueTemporaryPassword = issueTemporaryPassword;
window.viewOrder = viewOrder;
window.updateStatus = updateStatus;
window.logout = logout;
